### ISSUE TITLE
Добавить глобальную(?) переменную

### ISSUE THREAD

**Issue by romkaspb** [ifrogmedia/frontend#1]
Хотелось бы (возможно, что то такое есть) что то типа глобальной переменной mode.
Поясню:
в GG (а точнее в mojolicious) есть переменная mode - режим работы приложения. Их два (теоретически может быть больше) - development и production.
Для чего это нужно думаю пояснять не стоит.

Работая над гельвецией, я заметил что мне для целостности и одинаковой работы js скрипта тоже необходимо знать режим работы приложения (например, для бронирования разные урлы).

Идея моя вот в чем - я могу для тега html добавлять атрибут data-mojo-mode.
Было бы круто, если можно было бы из js получить режим работы приложения. GG.mode например. И от этого плясать в какие то вещи)

**Comment by ifrogmedia** [comment]
Имплементировано #bab41b6c52b13669301bfe8fed4412c31d22c69c
